version: "2"
services:
    app:
        image: node:latest
        container_name: app
        restart: always
        working_dir: /usr/src/app
        ports:
            - "3000:3000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
        environment:
            - NODE_PORT=3000
            - NODE_ENVIRONMENT=DEVELOPMENT
        command: bash -c "npm install -f && npm run dev"
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
