const titles = [
  'Honey Waffle ',
  'Message Wiz ',
  'Kweri ',
  'Rorschach Test ',
  'Erwin ',
  'Accurate Fortune Teller',
  'Philosopher ',
  'ACUMAN',
  'Anny ',
  'ALICE',
  'ALTAÏ ',
  'ANNA',
  'Arisa ',
  'Aztekium Bot',
  'Bariatric IQ ',
  'Braina',
  'Brain Bot',
  'Cadence digital assistant',
  'CHAT TO GOD!!',
  'CHERRY AI Chatbots',
  'cl0ne (zero inside clone)',
  'concepter',
  'ERWIN ',
  'ELIZA',
  'Eliza ',
  'Flow.ai ',
  'Cindy',
  'Haptik Personal Assistant',
  'Fun Time Chat AI Bots [1]',
  'Recimē Chatbot Platform',
  'Lea by Nett® ',
  'Web Hal (2007 Loebner 1st place)',
  'iBot',
  'Joan (2007 Loebner 2nd place)',
  'Kimbot',
  'Rembo – Reminder, Alarm and To',
  'The Personality Forge',
  'PennyCat – Find discounts in a second (Messenger bot)',
  'Jabberwacky',
  'Zero',
  'TWI',
  'Open Pandora',
  'Botster',
  'Colombina ',
  'Cleverbot',
  'Santa Bot',
  'TrilyoBot ',
  'DeBbie ONeiL free chatbot and AI book ',
  'SimSimi',
  'Job Pal',
  'Coupon Hippo (Messenger Bot)',
  'Abe',
  'Talking Bot',
  "Jessie's Story",
  'KWERI ',
  'Kurna the Klingon ',
  'PsychicMatic ',
  'Habla con Cervantes ',
  '¿Quién soy? ',
  'Instalocate ',
  'Wiredelta ',
  'Sourcing Bot ',
  'WBOT by SingaporeChatbots.sg',
  'MOTI AI, the Myers',
  'SPOCK',
  'Mitsuku',
  'The AssistantBot ',
  'Live Forever Project',
  'Elecktra B. Ing',
  'Luminous B. Ing',
  'Looney Bot',
  'RORSCHACH TEST ',
  'Machiko',
  'Morph.ai',
  'Julie Julie is your online girlfriend.',
  'Shaky ',
  'Florence.chat ',
  'NLPBots',
  'Toolwatch.io Messenger Bot ',
  'Delight',
  'Your.MD ',
  '123Lucky ',
  'Letstock ',
  'Yellow Messenger Telegram BOT',
  'Yellow Messenger FB Messenger BOT',
  '5Gifts4Her Messenger BOT',
  'Lisa',
  'Julia',
  'Júlia Bot',
  'FML Bot!',
  'Puny the Puffin A smart bot that gives you Book Suggestions',
  'MESSAGE WIZ ',
  'Wikipedia Bot ',
  'Talk2Me your friendly chatbot.',
  'Healee Chatbot ',
  'BOT libre! Create Twitter bots Facebook bots and more!',
  'Verloop.io ',
  'Bot Designers ',
  'Flow.ai ',
  'Inforobo AI Chatbot Platform',
  'Engati',
  'Haptik ',
  'Morph.ai The most complete chatbot platform',
  'Bottr',
  'BotMakr ',
  'Ask Nestor',
  'Recimē Chatbot Platform',
  'Microsoft Bot Framework',
  'myBot',
  'Bottr',
  'Octane AI',
  'Wit AI',
  'Recast AI',
  'Existor',
  'Gupshup ',
  'avaamo',
  'ChatBoten',
  'CleverBot',
  'Live Forever Project',
  'BOT libre! Create Twitter bots Facebook bots and more!',
  'Computer Software Skills',
  'doll RubyGems',
  'Git Hub',
  'rebot ME',
  'Pandorabots',
  'A.I. Pioneer',
  'LUIS',
  'Flow XO',
  'Botisfy',
  'The Personality Forge',
  'MindMeld',
  'Program O',
  'eContext',
  'Chatbots.io',
  'BrainShop',
  'Lingr',
  'LOVEdroids',
  'CleverScript',
  'Telegram Messenger',
  'Diffbot',
  'botmother.com',
  'BotSociety',
  'AI Assistant ',
  'Dr. Lal PathLabs ',
  'Ziman ',
  'Akancha Against Harassment ',
  'Housejoy ',
  'Times of India Personal Assistant',
  'Economic Times Personal Assistant',
  'Samsung MyGalaxy Personal Assistant',
  'Recimē Chatbot Platform',
  'Parlo Enterprise Chatbot Platform for HR anr IT bots',
  'All chatbots for skype',
  'Skyscanner bot',
  'Hipmunk bot',
  'Foursquare Skype bot',
  'Murphy bot for skype',
  'Your face chatbot',
  'BotMakr ',
  'Facebook Messenger chatbots',
  'Recimē Chatbot Platform',
  'Coca Cola Chatbot',
  'Restaurant Chatbot',
  'Real Estate Chatbot',
  'Outbrain personal news assistant',
  'Efficacy Tips',
  'Puny the Puffin A smart bot that gives you Book Suggestions',
  'Altaï A recruiting agent for AI Emergence adoption',
  'Skinive ',
  'Julie',
  'Recimē Chatbot Platform',
  'Brain Bot',
  'Telegram Bots',
  'Altaï the bot, A recruiting agent for AI Emergence adoption',
  'Recimē Chatbot Platform',
  'brainchatbot@gmail.com ',
  'Dating and Love Advice Bot',
  'Love Droids'
]
const descriptions = [
  ' Communicate better with message suggestions.',
  ' Translate your chat messages into text slang.',
  ' Quick questions that may drive you crazy.',
  ' Learn more about your personality.',
  ' Knotty riddles and clues to solve them.',
  ' Ask me deep philosophical questions',
  ' daily horoscope BOT',
  ' first chatbot to recruit humans to lead the Emergence, the massive adoption of AI.',
  ' gtalk / twitter',
  ' first bariatric diet chatbot',
  ' Knotty riddles and clues to solve them.',
  " I'm a virtual therapist that responds to your feelings, inspired by the original ELIZA natural language processing program",
  ' drag and drop chatbot design with powerful NLP',
  ' Got a question about girls issues? Just ask Lea!',
  'Do Chatbot',
  ' Emotional chatbot lady who loves synthwave music.',
  ' Conversational AI Bot for the hospitality industry',
  ' Quick questions that may drive you crazy.',
  'speaking chatbot)',
  ' AI powered personal travel assistant',
  ' The ultimate WordPress, Magento and Drupal assistant powered by wiredelta.com',
  ' Hi there! I am Sourcing bot. I help to find software developers and teams. Ask me anything about IT outsourcing ;)',
  'Briggs of habit formation',
  ' this bot is looking for an assistant',
  ' Learn more about your personality.',
  ' A personal bartender on Messenger',
  ' A Healthcare Chatbot',
  'Natural Language Processing bots',
  ' Find your next mechanical watch and take care of your watch',
  ' Your Personal Health Assistant & Symptom Checker Take control of your health Your.MD gives you personal, trusted and actionable , information – instantly.',
  ' Daily lucky signs horoscope BOT',
  ' Chatbot for sotck maret qoutes',
  ' Upgrade your texting! Translate your chat messages into text slang.',
  ' Voice enabled Bot to find any information from Wikipedia',
  ' Healee AI',
  ' Build Chatbots for individuals, startups and companies.',
  ' Free Bot Designer Platform',
  ' Conversational AI Toolkit',
  ' a chatbot platform',
  " India's Largest Chatbot Platform",
  ' build free chatbots with no programming and embed them in your website',
  ' Bot Builder Platform',
  ' AI Chatbot to assist designers on the KickyPie designer platform.',
  ' Test Booking, Branch Guide, and more.',
  ' 24/7 Chatbot Companion for Travel Safety',
  ' Resource for victims of cyber harrassment',
  ' Home Services Bot',
  ' Answers questions about the BotMakr website',
  ' Everyday Skin Symptom Checker'
]

const authors = [
  'Leandro Tenney',
  'Emiko Arana',
  'Fiona Leisure',
  'Felicitas Sommer',
  'Kimberely Mackenzie',
  'Robert Graybeal',
  'Amalia Rinehart',
  'Adell Verde',
  'Theodore Egli',
  'Trudi Mantooth',
  'Laura Maloof',
  'Suzi Matas',
  'Nita Mannon',
  'Kemberly Resendez',
  'Fredricka Bartley',
  'Aliza Spade',
  'Adelina Keitt',
  'Arnoldo Sturges',
  'Jacki Mattia',
  'Cherri Rohrbaugh',
  'Nakita Liddle',
  'Joseph Agar',
  'Lanell Heinen',
  'Karena Pan',
  'Felisha Bran',
  'Katherina Krohn',
  'Lissa Greenberg',
  'Sacha Beane',
  'Marketta Eleby',
  'Lourie Ligon'
]

const names = ['Roco', 'Manuel', 'Brigitte', 'Clara', 'Ferrara', 'Sifredi', 'Morgan', 'Macron']
const pseudos = ['Bamako', 'Booba', 'Batman', 'Kaaris']
const emails = ['@gmail.com', '@hotmail.com', '@j-m.fr', '@elpueblo.fr']
const passwords = ['azerty123', 'azertyuiop123', 'qsdfghjklm123', 'wxcvbn123']
const title = ['Lead generation', 'Feedback collection', 'Contact us', 'Get suscriber', 'Education consultancy']

const categories = ['messenger', 'slack', 'twitter', 'whatsapp']

const pickOneRandom = list => {
  return list[Math.floor(list.length * Math.random())]
}
const pickXRandom = list => {
  let ret = []
  const number_element = Math.floor(list.length * Math.random())
  for (let i = 0; i < number_element; i++) {
    let elem = pickOneRandom(list)
    if (!ret.includes(elem)) {
      ret.push(elem)
    }
  }
  return ret
}

export const getChatbotsExamples = (n = 10, id = null) => {
  let ret = []
  for (let i = 0; i < n; i++) {
    ret.push({
      title: pickOneRandom(titles),
      description: pickOneRandom(descriptions),
      chatbot_test_url: 'Un super url',
      langs: pickOneRandom(['fr', 'en']),
      chatbot_file: 'Un super url',
      author: id
    })
  }
  ret[0].promoted = true
  ret[1].promoted = true
  ret[2].promoted = true
  return ret
}

export const createUser = () => {
  return {
    firstName: pickOneRandom(names),
    lastName: pickOneRandom(names),
    pseudo: pickOneRandom(pseudos),
    email: pickOneRandom(names) + pickOneRandom(emails),
    password: pickOneRandom(passwords)
  }
}

export const createChatbot = () => {
  return {
    title: pickOneRandom(titles),
    description: pickOneRandom(descriptions),
    chatbot_test_url: 'Un super url',
    langs: pickOneRandom(['fr', 'en']),
    chatbot_file: 'Un super url'
  }
}
